name: Check

on:
  push:
    branches: [master]
    paths:
      - "src/**"
      - "public/**"
      - "package-lock.json"
  pull_request:
    branches: [master]
    paths:
      - "src/**"
      - "public/**"
      - "package-lock.json"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci
      - run: npm run lint
      - run: CI=true npm test
